# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-29 10:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RelationalApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='RelationalApp.Student'),
        ),
    ]
