# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-29 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('RelationalApp', '0002_auto_20190629_0338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='student',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='RelationalApp.Student'),
        ),
    ]
