# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-29 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RelationalApp', '0003_auto_20190629_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='student',
            field=models.OneToOneField(null=True, on_delete=models.SET(6), to='RelationalApp.Student'),
        ),
    ]
