# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2019-06-15 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbcckData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rollno', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('feedback', models.CharField(max_length=500)),
            ],
        ),
    ]
